### ISSUE TITLE
[버그 제보] 가게 수정시 버그 목록

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#35]
- 유효하지 않은 sns url => 아무런 작동 x
- 가게 이름 비우면 아무런 에러 없이, 화면 이동됨

**Comment by JeongJinyong** [comment]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/pull/47/commits/054e881af4ae9e6f6786929d4d385c59dc1b3113
