### ISSUE TITLE
[버그 제보] 위치 정보가 이상함 (null)

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#36]
![IMG_0758](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/d81d2b11-9066-48dc-8120-fc5205ed3123)

**Comment by JeongJinyong** [comment]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/pull/46/commits/ae9e14ee34061aebce1b14cb5dc93017468ca088

**Comment by seungh0** [comment]
이거 v0.0.2에서 계속 발생하고 있어서 재 이슈업합니다
