### ISSUE TITLE
[버그 제보] 랜딩 이미지 깨짐 현상 존재

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#37]
![IMG_0759](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/6d38e9fb-250f-4a5d-b5d8-82bc5f055db2)

**Comment by Minoyam** [comment]
45129c8320c1fdca0e12a21271d5072706064637

**Comment by seungh0** [comment]
0.0.1 정상 동작 확인 완료했습니다
