### ISSUE TITLE
[버그 제보] 메뉴 이미지 적정 크기로 유지가 필요해보입니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#38]
![IMG_0757](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/6234c457-4b17-4082-9d2d-abcb929e8f35)

이미지 크기가 커지면 화면을 다 잡아 먹는 중

**Comment by Minoyam** [comment]
887da826b3affd572c97771de4abbfe8facfd7ad

**Comment by seungh0** [comment]
0.0.1 확인 완료했습니다!!
