### ISSUE TITLE
[버그 제보] 첫 앱 켰을때, 서울시 중구로 표기됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#40]
- 현재 위치로 표기되어야 할거 같습니다

**Comment by JeongJinyong** [comment]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/pull/46/commits/ae9e14ee34061aebce1b14cb5dc93017468ca088
