### ISSUE TITLE
[버그 제보] 회원가입시 잘못된 입력인 경우 아무런 동작 X

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#41]
- 이름 등 미 입력 후 [가입 신청하기] 버튼 클릭시 미동작
- 사업자 등록 번호 포맷 안 맞거나 잘못된 경우 미동작

**Comment by Minoyam** [comment]
6bd9e6865d04fba59624e56e278d3dda097f7dc6

**Comment by seungh0** [comment]
0.0.1 확인 완료했습니다!!
