### ISSUE TITLE
[버그 제보] 가입 승인/거절시 푸시 알림이 안옴

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#43]
- 가입 신청할떄 푸시 토큰이 등록되지 않아서, 푸시 발송이 안되는 것으로 보입니다.
- 가입 신청시, 디바이스 등록도 같이 가능할까요?

**Comment by Minoyam** [comment]
디바이스 등록 코드는 넣어져있는데 푸시 알림 권한이 허용이 안돼있어서 그런거 같습니다.
푸시 알림 권한 물어보는걸 홈화면에 넣어놨는데, 스플래시나 로그인 페이지에서도 권한을 물어보게 변겅할게요!

**Comment by JeongJinyong** [comment]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/pull/46/commits/ae9e14ee34061aebce1b14cb5dc93017468ca088
