### ISSUE TITLE
[버그 제보] FAQ 최상단의 제목이 짤립니다ㅔ

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#44]
![IMG_0762](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/4789bb37-70ba-4792-8a8a-95f5660fccd4)

- “가입” 이라는 제목 안보이는 중``
- 기기: 갤럭시 s9

**Comment by Minoyam** [comment]
5d5fe229dbcddeb86745c199835e639f25b1273f

**Comment by seungh0** [comment]
확인 완료 했습니다~ (0.0.1)

**Comment by Minoyam** [comment]
한번 더 확인해보겠습니다!

**Comment by Minoyam** [comment]
수정할 때 스크롤 내렸다가 위로 올렸을 때 없어지는 이슈도 해결 했었는데, 확인해보니까 해상도 360까지 내리면 해당 이슈가 
발생하는 걸 확인했습니다.
위 아래에 주는 여백 때문에 생기는 문제인데 360 해상도 까지 맞추려면 아예 여백을 없애야 될 꺼 같아서 다른 해상도에 디자인에 문제가 갈 꺼 같습니다.
마이너한 부분이라 일단은 보류 해두는게 좋을 꺼 같습니다.

**Comment by seungh0** [comment]
넵~
