### ISSUE TITLE
[로그인 화면] 설치 후 맨 처음 로그인 시 토큰 세션 만료 버그

### ISSUE THREAD

**Issue by Minoyam** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#50]
모듈이 싱글톤화 되어 있어서 맨 처음에 토큰이 빈값으로 고정이 되어있어서 생기는 문제,
해결 방안을 생각 해봐야 할 꺼 같습니다.

**Comment by seungh0** [comment]
> 발생 버전: v0.0.2

로그인 된 상태에서 앱 새로 켰을때, 동일한 요청이 어마어마하게 들어가네요
- 내정보 조회
- 로그인 API
가 1초에 60건이 호출되서... RateLimit에 차단됩니다 ㅠㅠ


동일한 이슈인거 같다고 하셔서, 이슈 해결해주실때 같이 확인 부탁드리겠습니다!

**Comment by Minoyam** [comment]
4c576d518e388ddccc9d9475c1550dbfe116601e

**Comment by seungh0** [comment]
확인 완료했습니다 (0.0.3)
