### ISSUE TITLE
[회원가입] 회원가입 성공시 디바이스 등록 누락

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#53]
> 발생 버전: v0.0.2

- 초기에 회원가입 요청 성공한 후에 응답으로 넘어가는 세션으로 디바이스 등록 API 호출이 필요합니다

**Comment by Minoyam** [comment]
3371cbf50e9ed0f362bdc618dd00d6ba65b1185c

**Comment by seungh0** [comment]
확인 완료했습니다 (0.0.3)
