### ISSUE TITLE
가게 이미지 정보 변경시, 저장하기 버튼 활성화 안됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#62]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/a914c00e-8cbd-460a-a4ef-2d653663b6f2

- 이미지 변경시에도 저장하기 버튼이 활성화되어야 할거 같아요

**Comment by Minoyam** [comment]
62600ea30253c48d74bfc7a7408a6d951215bd01
