### ISSUE TITLE
출몰 지역은 Optional하게 입력할 수 있어야 합니다

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#63]
![IMG_2843](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/ad1b8b0f-7a58-4da2-8b4e-ea2df930f14c)

**Comment by Minoyam** [comment]
5a4703f1f1d9566b9f1e1d7cea89355dae50409b
