### ISSUE TITLE
메뉴 이미지 변경시 변경 안됨

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#64]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/8c7d56f4-78b3-4478-953e-1655ffba7b5a

**Comment by Minoyam** [comment]
해당 부분 확인해보니 이미지가 변경이 된거고 다른 페이지를 이동한 뒤 돌아오면 정상적으로 변경 돼 있더라구요
저장하기 버튼을 누른뒤 다시 가게 정보 페이지로 돌아 왔을 때 서버 로그에 있는 ImageURL과 기존에 가지고 있던 ImageURL을 비교 해봤는데 두 개의 ImageURL이 동일한 것을 발견했습니다.
그렇다면 메뉴를 수정한 뒤 바로 `@GET("v1/boss/store/me")` API를 호출 했을 때 수정된 ImageURL이 아닌 기존에 ImageURL을 가져 오는거 같은데,
현재 `ImageBulk api `-> `patch api` -> `get store me`순으로 호출하고 있습니다.
`ImageBulk api `->` patch api`를 호출 한 뒤에 너무 빠르게 `get store me`를 호출 한다면 ImageURL이 적용이 안되는 경우가 존재할 수 도 있을까요??

**Comment by seungh0** [comment]
@Minoyam 동기적으로 발생해서... ImageBulk api -> patch api를 호출 한 뒤에 너무 빠르게 get store me를 호출 한다면 ImageURL이 적용이 안되는 케이스는 없습니다

**Comment by Minoyam** [comment]
e9d8c5526b98cf68ade059a7d12b1692770428dd
