### ISSUE TITLE
메뉴 삭제시 메뉴 갯수 변경 안됨 + 전체 삭제시 크래시 발생함

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android#65]
https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-manager-android/assets/48153675/ebd355c8-8966-4b1c-9d7a-8fd34f41714e

- 메뉴 삭제시, 메뉴 카운트 감소되지 않음
- 메뉴 전체 삭제시 크래시 발생함

**Comment by Minoyam** [comment]
ab76eddee4b68959e2984aee5db9fa387a07d91d
